
name: Expense Pay Tests (sample)
on:
  workflow_dispatch: {}
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup bench (manual step required)
        run: |
          echo "This is a sample workflow. For production, install bench & create a test site then call .ci/run-tests.sh"
          echo "Skipping heavy setup in sample."
